# Load LLM API keys from ANTHEMIUM_VAULT into errorlogy-mas/.env (gitignored).
# Idempotent — safe to re-run. Never prints secret values.
#
# Usage (from repo root or errorlogy-mas):
#   .\scripts\load_keys_from_vault.ps1
#   .\scripts\load_keys_from_vault.ps1 -VaultPath "C:\Users\Public\ANTHEMIUM_VAULT\api_keys.md"

param(
    [string]$VaultPath = "C:\Users\Public\ANTHEMIUM_VAULT\api_keys.md"
)

$ErrorActionPreference = "Stop"
$MasRoot = Split-Path $PSScriptRoot -Parent
$EnvFile = Join-Path $MasRoot ".env"

# Vault label (lowercase) -> MAS env var name
$LabelMap = [ordered]@{
    "claude"                        = "ANTHROPIC_API_KEY"
    "chatgpt"                       = "OPENAI_API_KEY"
    "kimi"                          = "KIMI_API_KEY"
    "openrouter"                    = "OPENROUTER_API_KEY"
    "openrouter_anthemium_api_key"  = "OPENROUTER_API_KEY"
    "ai google studio"              = "GOOGLE_API_KEY"
    "deepseek"                      = "DEEPSEEK_API_KEY"
    "groq"                          = "GROQ_API_KEY"
    "agento genesis bot"            = "TELEGRAM_BOT_TOKEN"
}

if (-not (Test-Path $VaultPath)) {
    Write-Error "Vault file not found: $VaultPath"
}

$lines = Get-Content -Path $VaultPath -Encoding UTF8
$parsed = @{}
$i = 0
while ($i -lt $lines.Count) {
    $label = $lines[$i].Trim()
    if ($label -and $i + 1 -lt $lines.Count) {
        $candidate = $lines[$i + 1].Trim()
        # Key lines: non-empty, not a path, not curl/json, not starting with http
        if ($candidate -and
            $candidate -notmatch '^(curl|https?://|\{|\[|C:\\|/|\-H|\-X|\-d)' -and
            $candidate.Length -ge 8) {
            $key = $label.ToLower()
            if ($LabelMap.Contains($key)) {
                $envName = $LabelMap[$key]
                if (-not $parsed.ContainsKey($envName)) {
                    $parsed[$envName] = $candidate
                }
            }
            $i += 2
            continue
        }
    }
    $i += 1
}

$header = @(
    "# Auto-generated by scripts/load_keys_from_vault.ps1 - do not commit",
    "# Source: ANTHEMIUM_VAULT api_keys.md (local vault only)",
    ""
)

$body = @()
$written = @{}
foreach ($entry in $LabelMap.GetEnumerator()) {
    $envName = $entry.Value
    if ($parsed.ContainsKey($envName) -and -not $written.ContainsKey($envName)) {
        $body += "${envName}=$($parsed[$envName])"
        $written[$envName] = $true
    }
}

# Preserve optional gov ingest placeholders from .env.example when missing
$optional = @("EXA_API_KEY", "GOVINFO_API_KEY", "COURTLISTENER_API_TOKEN", "LEGISCAN_API_KEY")
foreach ($name in $optional) {
    if (-not ($body -match "^${name}=")) {
        $body += "${name}="
    }
}

$content = ($header + $body) -join "`n"
Set-Content -Path $EnvFile -Value $content -Encoding UTF8 -NoNewline
Add-Content -Path $EnvFile -Value "`n" -Encoding UTF8

$providers = @()
if ($parsed.ContainsKey("ANTHROPIC_API_KEY"))  { $providers += "anthropic" }
if ($parsed.ContainsKey("OPENAI_API_KEY"))     { $providers += "openai" }
if ($parsed.ContainsKey("OPENROUTER_API_KEY")) { $providers += "openrouter" }
if ($parsed.ContainsKey("GOOGLE_API_KEY"))     { $providers += "google" }
if ($parsed.ContainsKey("DEEPSEEK_API_KEY"))   { $providers += "deepseek" }
if ($parsed.ContainsKey("GROQ_API_KEY"))       { $providers += "groq" }
if ($parsed.ContainsKey("KIMI_API_KEY"))       { $providers += "kimi" }

Write-Host "Keys loaded into $EnvFile"
Write-Host "Mapped env vars: $($parsed.Keys -join ', ')"
Write-Host "Available providers: $($providers -join ', ')"
Write-Host "OAuth (api/auth): not used for batch eval - API keys only"
